package com.sskj.hangqing.bean;

public class SelfCoinBean {
    /**
     * id : 1
     * type : 4
     * name : 比特币（Bitcoin）
     * code : BTC/USDT
     * engname : null
     * category : null
     * market : null
     * createTime : null
     * isDeleted : false
     * timestamp : 1565170388000
     * publishTime : 1541058965000
     * publishNum : 21000000
     * publishPrice : null
     * publishWeb : null
     * whitePaper : null
     * remark : 比特币（Bitcoin，简称BTC）是目前使用最为广泛的一种数字货币，它诞生于2009年1月3日，是一种点对点（P2P）传输的数字加密货币，总量2100万枚。比特币网络每10分钟释放出一定数量币，预计在2140年达到极限。比特币被投资者称为“数字黄金”。比特币依据特定算法，通过大量的计算产生，不依靠特定货币机构发行，其使用整个P2P网络中众多节点构成的分布式数据库来确认并记录所有的交易行为，并使用密码学设计确保货币流通各个环节安全性，可确保无法通过大量制造比特币来人为操控币值。基于密码学的设计可以使比特币只能被真实拥有者转移、支付及兑现。同样确保了货币所有权与流通交易的匿名性。
     * remarkUS : Bitcoin (BTC) is currently the most widely used digital currency. It was born on January 3, 2009. It is a kind of digital encryption currency transmitted by point-to-point (P2P) with a total amount of 21 million. Bitcoin releases a certain amount of money every 10 minutes and is expected to reach its limit in 2140. Bitcoin is called "digital gold" by investors. Bitcoin is generated by a large number of calculations based on a specific algorithm, and does not rely on the issuance of a specific monetary institution. Bitcoin uses a distributed database composed of many nodes in the whole P2P network to confirm and record all transactions, and uses cryptographic design to ensure the security of all links of currency circulation, so as to ensure that it can not pass through a large number of transactions. Bitcoin is manufactured to manipulate the value of the currency artificially. The cryptographic design allows Bitcoin to be transferred, paid and cashed only by the real owner. It also ensures the anonymity of currency ownership and circulation transactions.
     * coinType : 2
     * coinOutType : 1
     * currencyNum : 16738200
     * queryBlock : null
     * coinArea : 1
     * coinImg : null
     * sort : null
     * select : true
     */

    private String id;
    private int type;
    private String name;
    private String code;
    private Object engname;
    private Object category;
    private Object market;
    private Object createTime;
    private boolean isDeleted;
    private long timestamp;
    private long publishTime;
    private String publishNum;
    private Object publishPrice;
    private Object publishWeb;
    private Object whitePaper;
    private String remark;
    private String remarkUS;
    private int coinType;
    private int coinOutType;
    private String currencyNum;
    private Object queryBlock;
    private int coinArea;
    private Object coinImg;
    private Object sort;
    private boolean select;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public Object getEngname() {
        return engname;
    }

    public void setEngname(Object engname) {
        this.engname = engname;
    }

    public Object getCategory() {
        return category;
    }

    public void setCategory(Object category) {
        this.category = category;
    }

    public Object getMarket() {
        return market;
    }

    public void setMarket(Object market) {
        this.market = market;
    }

    public Object getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Object createTime) {
        this.createTime = createTime;
    }

    public boolean isIsDeleted() {
        return isDeleted;
    }

    public void setIsDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    public long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

    public long getPublishTime() {
        return publishTime;
    }

    public void setPublishTime(long publishTime) {
        this.publishTime = publishTime;
    }

    public String getPublishNum() {
        return publishNum;
    }

    public void setPublishNum(String publishNum) {
        this.publishNum = publishNum;
    }

    public Object getPublishPrice() {
        return publishPrice;
    }

    public void setPublishPrice(Object publishPrice) {
        this.publishPrice = publishPrice;
    }

    public Object getPublishWeb() {
        return publishWeb;
    }

    public void setPublishWeb(Object publishWeb) {
        this.publishWeb = publishWeb;
    }

    public Object getWhitePaper() {
        return whitePaper;
    }

    public void setWhitePaper(Object whitePaper) {
        this.whitePaper = whitePaper;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getRemarkUS() {
        return remarkUS;
    }

    public void setRemarkUS(String remarkUS) {
        this.remarkUS = remarkUS;
    }

    public int getCoinType() {
        return coinType;
    }

    public void setCoinType(int coinType) {
        this.coinType = coinType;
    }

    public int getCoinOutType() {
        return coinOutType;
    }

    public void setCoinOutType(int coinOutType) {
        this.coinOutType = coinOutType;
    }

    public String getCurrencyNum() {
        return currencyNum;
    }

    public void setCurrencyNum(String currencyNum) {
        this.currencyNum = currencyNum;
    }

    public Object getQueryBlock() {
        return queryBlock;
    }

    public void setQueryBlock(Object queryBlock) {
        this.queryBlock = queryBlock;
    }

    public int getCoinArea() {
        return coinArea;
    }

    public void setCoinArea(int coinArea) {
        this.coinArea = coinArea;
    }

    public Object getCoinImg() {
        return coinImg;
    }

    public void setCoinImg(Object coinImg) {
        this.coinImg = coinImg;
    }

    public Object getSort() {
        return sort;
    }

    public void setSort(Object sort) {
        this.sort = sort;
    }

    public boolean isSelect() {
        return select;
    }

    public void setSelect(boolean select) {
        this.select = select;
    }
}
